### ISSUE TITLE
file zip or not

### ISSUE THREAD

**Issue by shrek232** [MindustryINSIDE/HackerTools#17]
When i go to into mod folder, its zipped
I also dont see anything new. So unzip?

**Comment by n-shift** [comment]
uhmmmm, excuse me, but are you serious?

**Comment by antsif-a** [comment]
Install mod from README's instructions, then in sandbox in logic block category you will see terminal block.

**Comment by Remint32** [comment]
@shrek232 Write the version and build of the game and the version of the mod that you are using
